# Generated by Django 4.0.4 on 2022-05-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Article', max_length=35, verbose_name='Name')),
                ('article_info', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(verbose_name='Date of publication')),
            ],
        ),
    ]
