# Generated by Django 4.0.4 on 2022-05-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='articles',
            name='anons',
            field=models.TextField(default=1, max_length=250, verbose_name='Anons'),
            preserve_default=False,
        ),
    ]
