# Generated by Django 4.0.4 on 2022-05-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articles_options_articles_anons'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='full_text',
            field=models.TextField(default=1, verbose_name='Full text'),
            preserve_default=False,
        ),
    ]
