# Generated by Django 4.0.4 on 2022-05-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=35)),
            ],
        ),
    ]
